"""initial

Revision ID: 235736ee8a4b
Revises:
Create Date: 2025-09-01 18:59:55.119099

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "235736ee8a4b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=50), nullable=False),
        sa.Column("password", sa.VARCHAR(length=60), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
